# Generated by Django 3.2.16 on 2023-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230410_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название сообщества не должно быть длиннее 200 символов', max_length=200, verbose_name='Название группы')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес группы')),
                ('description', models.TextField(help_text='Добавьте описание сообщества.', verbose_name='Описание группы')),
            ],
            options={
                'verbose_name': 'Группа',
            },
        ),
    ]
